<?php

namespace AppBundle\Repository;

/**
 * AuthorsBooksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorsBooksRepository extends \Doctrine\ORM\EntityRepository
{
}
